### ISSUE TITLE
Enabling scheduling privilege - user not able to create meeting

### ISSUE THREAD

**Issue by briannwar** [jrchamp/moodle-mod_zoom#265]
Hi.... I'm testing the latest version of the Zoom plugin (v3.7, 2021041300) on our Moodle 3.10.4 (2020110904) test site. The "Enable scheduling privilege option" is on (this is a new admin setting in 3.7). This is the test I'm conducting where I'm seeing a problem:

-- User A and User B are instructors in the Moodle course.
-- In his Zoom settings, User B has assigned scheduling privileges to User A
-- User A is logged in to Moodle and goes to add a Zoom Meeting instance to the course
-- User A sees that he can schedule the meeting for both User B and User A ("Yourself").
-- When User A tries to schedule for himself (UserA), he get's an error ("You cannot schedule for the specified user") -- see link below for screenshot.

![zoom problem](https://user-images.githubusercontent.com/85974283/122251624-860b7b80-ce7f-11eb-8a5c-0495f1f85b8f.png)

User A is able to create a Zoom meeting instance for User B. And User A is able to schedule a meeting when User B is not an instructor in the course (i.e., the "Schedule meeting for" option is not present). The error is produced when the "Schedule meeting for" option is present, and User A tries tries to create a meeting for himself.

Please let me know if there might be any settings that would address this problem, or if you have any questions. I can also submit an issue to the GitHub repo is that would help.

Thanks much... Brian Warling (UCSF)

**Comment by briannwar** [comment]
Hi..... I'm assuming that this bug has been confirmed. I'm wondering if there are plans to fix this critical issue soon. 

Please let me know if I can provide any more information.  

Thanks... Brian Warling

**Comment by jrchamp** [comment]
Hi @briannwar! Yes, the bug has been assigned. Once it is fixed and merged, we'll be planning a release.

To speed the process, it may help to have one piece of clarity: When does the error message first show up?
 * when the page first loads
 * when you select "Yourself"
 * when you try to save/create the meeting

Also, thank you for reporting this issue! We really appreciate it.

**Comment by briannwar** [comment]
Hi @jrchamp .... Thanks for getting back on this. The error appears when you try to save/create the meeting (with "Yourself" selected). I hope this helps..... Brian

**Comment by jrchamp** [comment]
Thanks Brian! That should mean that it's failing in the form's validation() function, likely in the schedule_for code: https://github.com/ncstate-delta/moodle-mod_zoom/blob/026fff48321f648012e85dd1dbe094ee98b0d9ec/mod_form.php#L556-L569

@armccoy The big question is probably what value `$data['schedule_for']` is set to, because if it was set to `$USER->email`, then it should be fine. I'm wondering if maybe it's empty and instead of `isset()`, we should be checking `!empty()`. Hope that helps.

**Comment by briannwar** [comment]
Hi....I'm wondering if there's any update on this issue? Please let me know if you have any questions or need any assistance. Thanks... Brian

**Comment by SarkanDev** [comment]
Hi, I’m new to integrating Moodle with Zoom. I’ve already connected Moodle with Zoom using a Server-to-Server OAuth app and added all the required scopes. The integration works, but the option to schedule meetings for another user is not showing up.

My Moodle account has a Zoom license, and I also assigned two additional licenses so that I should be able to schedule meetings for those two emails. However, the scheduling-for-others option still doesn’t appear inside Moodle.

Is there something I might be missing? Any help would be greatly appreciated. Thank you!
