### ISSUE TITLE
join_url not saved when I change password in activity module

### ISSUE THREAD

**Issue by selimmeziti** [jrchamp/moodle-mod_zoom#303]
If I change the password in activity module, the password is correctly save in Zoom account and bdd Moodle.
But the join_url isn't saved in bdd moodle.
join_url contains the encrypted password, if a student wants to join a meeting, he will have to enter the password because the one in the url is different than the one registered in the Zoom account.
Otherwise the start_url is always different but no problem. Zoom must surely modify them permanently, maybe a security issue

**Comment by jrchamp** [comment]
In looking at the code, it doesn't look like the updated `join_url` ever has a chance to be saved to the database due to the code order:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/8981109c7c1eca90386362fe2d658c9bd9bb4ed9/lib.php#L160-L182

As partially discussed in #302, the code order should probably be changed to:

1. If there are changes, send the changes to Zoom.
2. If the Zoom changes succeeded, update Moodle.

The potential downside is that a single error by the user will prevent any data from being saved by Moodle. It would be a bigger problem if the amount of effort to create a Zoom activity was significant, but it seems like we're in a worse situation by saving incorrect information as if it were correct.

**Comment by selimmeziti** [comment]
I think join_url is not updated in Moodle because normally join_url does not change.
But if you enable the option to include the encrypted password in the url to join the meeting, then join_url contains the password pwd=xxx. so join_url changes as soon as you change the password.
Is it possible to fix this problem in the plugin ?
Thanks

**Comment by smbader** [comment]
The simple fix is to add another update_record for zoom after getting the meeting_webinar_info and populating our zoom object. This assures we match what is on Zoom's side of things.

If we wanted to optimize this function a bit further, we could call update_record for zoom less frequently. For example, I'm unsure of the need for the update on line 175 (the first). In the future, refactoring this function would be beneficial.

For now, I'd like to fix the issue at the very small performance cost of an extra update.

**Comment by smbader** [comment]
Testing Instructions:

- Create a Zoom activity in Moodle.
- Assure you're logged out of your Zoom app.
- Click the join link and confirm the join_url works to connect to the meeting.
- Close the meeting.
- Edit the settings for the Zoom activity.
- Change the passcode to the meeting and hit save.
- Verify the join link has changed and that you can still connect to the meeting.
-
