### ISSUE TITLE
Database schema is not aligned - index for uuid in zoom_meeting_details table

### ISSUE THREAD

**Issue by TomoTsuyuki** [jrchamp/moodle-mod_zoom#334]
I found 'Database schema is not aligned.' error in 'Database schema check' in 'Performance overview' from one of our client. 
zoom_meeting_details
Unexpected index 'mdl_zoommeetdeta_uui_uix'.

I found the codes the index included in upgrade.php, but not install.xml
https://github.com/ncstate-delta/moodle-mod_zoom/blob/3a2d1c2784c63ed83881954bd2e79b50de265c9f/db/install.xml#L70
https://github.com/ncstate-delta/moodle-mod_zoom/blob/3a2d1c2784c63ed83881954bd2e79b50de265c9f/db/upgrade.php#L215

So it probably like:
The mod_zoom is installed before 15 Sep 2018.
Upgrade script added the index.
Schema check process finds difference between install.xml and db schema.

Do we need the index for uuid in zoom_meeting_details table?
If yes, can you add it into install.xml?
If no, I'll remove the index from the our db.

**Comment by TomoTsuyuki** [comment]
I was trying to add the unique index `uuid_unique`  to `zoom_meeting_details` table, but it looks `array('meeting_id', 'uuid')` is unique, not sure `uuid_unique`?
I don't have real records and not sure I can add the index.
https://github.com/ncstate-delta/moodle-mod_zoom/blob/3a2d1c2784c63ed83881954bd2e79b50de265c9f/db/upgrade.php#L215-L218
Is `uuid` unique in `zoom_meeting_details` table?

**Comment by TomoTsuyuki** [comment]
I made PR #335 to fix this issue.
Please review and merge if it's ok.

**Comment by jrchamp** [comment]
Hi @TomoTsuyuki, sorry for the delay in replying (I'm on vacation).

It looks like you are correct that the index was added in upgrade.php, but not added in install.xml. However, that may have been because the index is not being used by the current code (it would depend on the query plan optimizer of each database). `uuid` should be unique all of the time as it is the less-glamorous meeting unique ID that is used by the Zoom API. Unfortunately, the code currently uses meeting_id either alone or in conjunction with uuid which would prevent us from dropping the wasteful meeting_unique index without additional changes. Though, I do think that correcting both issues is a good idea.

As this is part of delete, this code should be using `'zoomid' => $zoom->id` to accurately delete matching entries:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/3a2d1c2784c63ed83881954bd2e79b50de265c9f/lib.php#L357-L361

Similarly, `zoom_get_sessions_for_display()` is trying to get all of the related session information for the Zoom activity. The function definition, the documentation and the get_records() call should all be using `$zoomid` / `'zoomid' => $zoomid`:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/6185efce53c963e96b00d2fd4c698a111c50ca11/locallib.php#L304-L314

These are the two places that `zoom_get_sessions_for_display()` is called. Both should be passing in `$zoom->id`:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/f881c4953abc1169f56f74fccda9ec43497af339/report.php#L51
https://github.com/ncstate-delta/moodle-mod_zoom/blob/f881c4953abc1169f56f74fccda9ec43497af339/participants.php#L62

With the addition of the unique index on `uuid`, these queries can be simplified by removing the unnecessary `'meeting_id' => $meeting->meeting_id` clauses:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/3a2d1c2784c63ed83881954bd2e79b50de265c9f/classes/task/get_meeting_reports.php#L467-L475

The last step would be to drop the meeting_unique index in both upgrade.php and install.xml.

**Comment by TomoTsuyuki** [comment]
Hi @jrchamp ,

Thanks for your reply.

I remove the `meeting_unique` key, and changed the codes accordingly.
I pushed the codes #335 .
Please let me know something wrong from my PR.
