### ISSUE TITLE
Recurring weekly meetings: Incorrect times created when setting a start date/time before time of activity creation

### ISSUE THREAD

**Issue by nchan31** [jrchamp/moodle-mod_zoom#341]
Steps to reproduce:
1. Add a Zoom activity
2. Click on "This is a recurring meeting:
3. Select "Weekly" under Recurrence
4. Choose a date or time that is before the current date/time. For instance, it is currently 5:30p, Dec 8. I'll choose Dec 7, 12p.
5. Choose a day of the week - I'll choose Tuesdays.
6. Set other settings as needed.
7. Save activity.

Expected result:
Meetings are created beginning next Tuesday, noon.

Actual result:
Meetings are created beginning next Tuesday, 5:33p (the time when I confirmed my settings and created the activity). Subsequent meetings in that recurrence will also have the same incorrect time.

Tested this with daily and monthly recurrence, and it works as expected.

Tested this in versions v4.1.1 and v4.3.

**Comment by jwalits** [comment]
I did some brief testing on this and it appears as though the data coming back from the Zoom API is a problem. The recurring meeting events in Moodle are created based on the data that comes back from the Zoom API once the meeting is created on that account. I believe the issue is on the Zoom side of things, rather then the plugin code.

Attaching a couple of screenshots of what data is being sent from Moodle and what is being returned from the API.

The data sent to Zoom:
![2021-12-17_17-10](https://user-images.githubusercontent.com/56375964/146498009-46398ffe-6128-4c17-89e7-cfaededb408f.png)

The data in the occurrences object returned back from zoom:
![2021-12-17_17-18](https://user-images.githubusercontent.com/56375964/146498549-e43193f3-59c1-4e4b-b023-14271b7ee547.png)

I'm not sure at this stage what we can do on the plugin side that will reflect the correct times when data is returned back from zoom in this use-case.

**Comment by jrchamp** [comment]
Thanks for testing this @jwalits. Even if it is a Zoom bug, we might be able to avoid it by detecting that the start_time is in the past and then calling `$start_time = strtotime('+1 day', $start_time);` until it's in the future?

**Comment by jwalits** [comment]
Thanks for the feedback @jrchamp. I agree that the plugin should set the start_time to be in the future. I'm happy to test/make that change if it makes sense from a business point of view?

I'm not totally sure whats the use case for adding a meeting with a start_time in the past?

**Comment by nchan31** [comment]
> I'm not totally sure whats the use case for adding a meeting with a start_time in the past?

Thanks, all, for looking into this! The start_time in the past came up mainly as a user error, in a way, but since there is no error message or adjustment made on the plugin side (similar to daily and monthly recurrence), it can cause incorrect meeting times to show up. This isn't immediately noticeable unless the user goes back into activity to check or check other blocks, such as the calendar.

**Comment by jwalits** [comment]
Thanks @nchan31 for the feedback. If its a case of user error, I'd be more tempted to add some error handling so it wont let you create a new meeting or update a meeting to set time in the past?

@jrchamp - I saw this code in the validation. https://github.com/ncstate-delta/moodle-mod_zoom/blob/master/mod_form.php#L699-L703 - The start_time is allowed to be in the past for recurring meetings? We could possibly just remove the `if (empty($data['recurring']))` so for all meetings it would not accept start_time in the past?

**Comment by jrchamp** [comment]
That would be a good idea, but it causes problems for people who are trying to edit the Zoom activity for unrelated changes (because the meeting is in the past). See #297 

Most likely we only test that the start time is valid in the situation where the value is being modified (either set for the first time or changed to a new value). A solution like that would provide feedback to a recurring user (addressing this current issue) and help resolve the other issue related to the inability to edit past activities.

**Comment by rickbeasley** [comment]
I've experimented with this code and think the basic problem is that the Date field means something different for recurring meetings than it does for one-time meetings. For a recurring meeting, the Date field's time portion is used to determine the start time of the meeting and the date portion is the first possible date to calculate the next meeting based on other recurring settings. A possible enhancement would be to visually treat the Date field differently when the user clicks "This is a recurring meeting" checkbox, maybe separating date and time with more explanatory labels.When I programmatically updated the start time to
