### ISSUE TITLE
Activity states that recurring meeting is not found, but it exists and can be used

### ISSUE THREAD

**Issue by cdipe** [jrchamp/moodle-mod_zoom#346]
We run moodle 3.9.7 and recently upgraded to Zoom Meetings v4.3.
Now when entering the activity it states that the meeting cannot be found on Zoom.
But the meeting exists in Zoom and can still be started and joined with the Join link.

![image](https://user-images.githubusercontent.com/14754240/146003072-2d681950-ac2e-417e-8fe7-b108fa67110d.png)

![image](https://user-images.githubusercontent.com/14754240/146003558-15fa37ed-a49f-42e3-84b4-c7d8630e16dc.png)

![image](https://user-images.githubusercontent.com/14754240/146003283-bb4b992c-5cf0-402b-91e2-64c44d9e7977.png)

**Comment by jrchamp** [comment]
Is this an issue for new meetings or is it only a problem for this meeting? I wonder if this was due to the AWS issues that were happening earlier this month. You can try setting the "exists_on_zoom" value to `1` in the database to see if that resolves the problem long term.

**Comment by emmarichardson** [comment]
I have also seen this message suddenly start showing up.  We use a course template with zoom meeting included to create all new courses.  I updated the database as noted above and will report back if the message reappears.

**Comment by jrchamp** [comment]
Thank you @emmarichardson for providing your feedback. I'm very interested to know if you encounter more of these.

I have noticed that some of my Zoom automation scripts have been experiencing timeouts. It's possible that these meetings are being marked as expired when a timeout occurs while contacting Zoom's API. That may mean that we need to more carefully check the response codes to differentiate between "does not exist" and "request timed out". I've checked the places where ZOOM_MEETING_EXPIRED gets set, but all of them appear to already be checking that the response from the API is one of the three "not exist" error codes.

**Comment by marcellobarile** [comment]
I'm also experiencing the same issue on some courses, actually digging into it but would be nice to get some official hints

**Comment by jrchamp** [comment]
Hints? Can do. First, I searched for the code that shows "meeting cannot be found on Zoom". It's coming from the language string `zoomerr_meetingnotfound`, which is used on the view.php page when `$showrecreate` is `true` which is set when `$zoom->exists_on_zoom == ZOOM_MEETING_EXPIRED`. So then I searched for places that set `exists_on_zoom` to `ZOOM_MEETING_EXPIRED`.

I found three ways for the Zoom meeting to be marked as expired.

In view.php, the plugin checks to see if the Zoom meeting exists on Zoom and gets the host from Zoom. If the response from Zoom is that the meeting or the user does not exist, it will mark it as expired in Moodle:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/13a1f5e3e017e5502202eabe92203df7052a1bd7/view.php#L74-L93

In the update meetings task, the plugin checks to see if the Zoom meeting exists on Zoom. If the response from Zoom is that the meeting does not exist, it will mark it as expired in Moodle:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/13a1f5e3e017e5502202eabe92203df7052a1bd7/classes/task/update_meetings.php#L84-L97

When restoring a Zoom activity, the plugin tries to create a new meeting using the saved data. If an exception occurs (because the new meeting is not created), then the Zoom activity is marked as expired:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/13a1f5e3e017e5502202eabe92203df7052a1bd7/backup/moodle2/restore_zoom_stepslib.php#L66-L75

The next step is to track when/where it occurs. One way would be to add some code to each location that logs what/when/why it happened. It could log to a file, the database, to an API, send an email or some other persistent store.

Hope that helps!

**Comment by marcellobarile** [comment]
thanks @jrchamp; in my case, I think that there might be some timeout in the "get_meeting_webinar_info" method which gets caught and causes the meeting to be marked as expired. I say this because all my courses actually exist on zoom but in some cases, they are marked as expired.

I was wondering to implement some sort of retry mechanism in the "get_meeting_webinar_info" method when a timeout occurs. Do you think that it could be a good solution?

**Comment by jrchamp** [comment]
@marcellobarile Maybe... it all depends on what's really happening. When I'm looking at the code, it looks like timeouts should fail in a different way. Testing what happens when there is a timeout would be good. Also, if it is a timeout, we may want to increase the allowed timeout before putting it in a retry loop that repeatedly times out. Conversely, if you wanted to test what a timeout situation returns, you could lower the allowed timeout to 1 second (or maybe lower, depending on the granularity of the timeout configuration).
