### ISSUE TITLE
Start Meeting does not appear & Register button does not appear for student when required registration

### ISSUE THREAD

**Issue by zishanj** [jrchamp/moodle-mod_zoom#442]
2 probably bugs were found in the code:

1. Start Meeting button does not appear due to wrong var used `$userisrealhost` instead of `$userishost`. ([source](https://github.com/ncstate-delta/moodle-mod_zoom/blob/d879442cd055314cb7630cf48d28dedcbd4eb8e7/locallib.php#L1049))
2. If required registration feature is enabled then Register button does not appear for student. [Lines 1026 ... 1035](https://github.com/ncstate-delta/moodle-mod_zoom/blob/d879442cd055314cb7630cf48d28dedcbd4eb8e7/locallib.php#L1026) needs to be revised for setting var `$available` to true.

**Comment by jrchamp** [comment]
Hi @zishanj,

Thank you for reaching out. Upon further review, I do believe there are some issues, but not exactly the ones you have listed.

`$userisrealhost` is intentional there - only the true host should have access to the start_url (which is also covered by the comment)
https://github.com/ncstate-delta/moodle-mod_zoom/blob/d879442cd055314cb7630cf48d28dedcbd4eb8e7/locallib.php#L1049-L1050

Everyone other than the true host should get the join URL for meetings that do not require registration.

For meetings that require registration:
 - the true host should still get the start URL
 - unregistered students should be sent to the join URL so they can register
 - registered students should be sent to the user-specific registered join URL

All of that seems to be working based on my reading of the code, albeit somewhat inefficiently where it appears to try and look up information for users even if that API request is not necessary.

The piece for meeting that require registration which I believe to be missing:
 - alternative hosts should always get the join URL and never be asked to register

These 7 test cases (registration required yes/no; host/alt host/student (registered and not registered)) clearly need to be tested to make sure they are working currently (and re-tested if we make any changes to the underlying code to try and fix them the non-working cases).

**Comment by jrchamp** [comment]
I've done some testing and it seems like the advanced checkbox isn't working any more. My plan is to switch that piece to a select list because I think it's a bug in the advanced checkbox code related to MDL-76095.

**Comment by jrchamp** [comment]
Student registration was fixed in [v4.9.2](https://github.com/ncstate-delta/moodle-mod_zoom/releases/tag/v4.9.2). We're preparing to test the alternative host experience.

**Comment by jrchamp** [comment]
@sgrandh3 and I tested the alternative host experience and it does work seamlessly if the alternative host is already logged in to the Zoom website. The registration page also correctly lets the alternative host know that they do not need to register for the meeting. I'll open a separate "known" issue that specifically addresses this shortcoming in the alternative host user's experience and ask for help, because I'm not sure how to improve it.
