### ISSUE TITLE
PHP 8.0 warning

### ISSUE THREAD

**Issue by Menrath** [jrchamp/moodle-mod_zoom#468]
Warning: Undefined property: moodle_exception:: $zoomerrorcode in mod/zoom/locallib.php on line 537

**Comment by jrchamp** [comment]
Thanks @andremenrath!

I think there are several situations where we are assuming that the zoomerrorcode property exists because we're only trying to handle the Zoom API's official responses. I have an idea that should help though, having all of the specific zoom exceptions extend a single generic zoom exception class that we can then use in our try/catch clauses.
