### ISSUE TITLE
Connection status: Connection failed: Invalid access token, does not contain scopes: [user:write:admin, user:read:admin, user:read, user:write].

### ISSUE THREAD

**Issue by tbeachy** [jrchamp/moodle-mod_zoom#474]
We previously had the Zoom plugin working with JWT.  I have emptied those fields and created a new server-to-server app and updated the plugin settings with the appropriate API credentials.
Now, when I update the settings page, I get the error:
`Connection status: Connection failed: Invalid access token, does not contain scopes: [user:write:admin, user:read:admin, user:read, user:write].`

In the Zoom app scopes, I can find and add user:write:admin, and user:read:admin, but there is no "[user:read]" or "[user:write]".

I am on Moodle 3.9.4 with the 4.10 version of the Zoom plugin.

I have verified all the credentials multiple times.  There are no leading or trailing spaces.  I have de-activated and re-activated the app, as well as creating a new one and using its credentials.  Nothing helps.

Please let me know what I'm missing, or if this is a bug.
Thank you.

**Comment by tbeachy** [comment]
Interesting... I decided to check it again this morning, based on other comments I've seen here, and it is now showing "connection working".  I haven't tested an actual Zoom meeting yet, but thought I would provide this update first. 
There must be a delay on the Zoom side, even though it appears to make changes immediately when in the app marketplace. 
Perhaps documentation/error messages need to be updated to reflect a possible delay, and the fact that there are no [user:read, user:write] scopes in the Zoom.

**Comment by jrchamp** [comment]
Hi @tbeachy,

I'm glad you were able to get it working. There may indeed be a delay, so we can try to add a note there, particularly because this has happened to a few people.

A note on scopes: Server-to-Server OAuth apps have account-wide access. So every possible Server-to-Server scope is going to have either `:admin` or `:master`. `:admin` scopes provide account-wide access. `:master` scopes extend access to sub-accounts. When accessing a given API function, such as [Get a user
](https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/user), there are a series of scopes listed (in this case, "user:read:admin, user:read, user_info:read"). To be able to use the API function, you only need to have one of those scopes. In our case, the only one that we need - or can even user - is `user:read:admin`. So it's not that Zoom's error message is saying "you need all four of these", but rather "you don't have any of these". That's especially confusing, because you definitely did grant access.

Now, what may be happening is that Zoom gave us a token which - due to caching or a delay - does not have the scopes we need. Thankfully, when they give us the token [Zoom does tell us which scopes are available to us](https://developers.zoom.us/docs/internal-apps/#successful-response). So maybe what we need to do is verify that the three required scopes are available in the token before we cache it. That may explain why it's not working for an hour or so and then it just "starts working".

**Comment by tbeachy** [comment]
Thanks for the explanation, and for looking into it!
Tim
