### ISSUE TITLE
Waiting room and Join before host enabled at once

### ISSUE THREAD

**Issue by hanirok** [jrchamp/moodle-mod_zoom#491]
Hello,

When creating a zoom session with one of the latest versions of the plugin, in Moodle 3.9, if the waiting room option is disabled, it re-enables itself, I think due to a security requirement, leaving both options enabled: "Waiting room" and "Join before host".

![2023-06-06 20_39_33-Editing Zoom meeting](https://github.com/ncstate-delta/moodle-mod_zoom/assets/1064771/d25046e8-777f-4ea5-a38a-2694e4ece3df)

**Comment by jrchamp** [comment]
Hi @hanirok,

Indeed, Zoom itself typically requires at least one security method and defaults to Waiting room if both Passcode and Authentication are not enabled. That is probably not related to the Moodle version or the plugin version, but is most likely to be a settings in your Zoom enterprise.

Side note: Join before host is not really a security option. If anything, it's the reverse because it allows more people to start the meeting instead of only the Host or the Alternative Hosts.

**Comment by Urpokarhu1** [comment]
Hello,
When I disable all security features on the Moodle side, waiting room is still forced on the Zoom-side. Is there any fix for this?

**Comment by smbader** [comment]
Hello Jari,

Zoom does not allow you to disable all security features. Please see this Zoom support article: https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0059862

Hope this helps!
Steve
