### ISSUE TITLE
Database schema is not aligned - column 'registration'

### ISSUE THREAD

**Issue by michael-milette** [jrchamp/moodle-mod_zoom#563]
Good day!

When I go to **Site Administration > Reports > Performance Overview**, I see the following message:

<img width="575" alt="image" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/3808579/6f564ca7-68dd-49d8-bd5c-73a3cc58f7c6">

When I click on **Database Schema Check** or **More info**, I see the following details:

<img width="480" alt="image" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/3808579/f3ef9a30-a4f6-4819-b365-126d39cd54c3">

Details text from the above screenshot:

**Zoom**

    column 'registration' should be NOT NULL (I)
    column 'registration' has default 'NULL', expected '2' (I)

Additional information:

- PHP: 8.2
- Moodle: 4.3.2+
- Zoom meeting: v5.1.4 | 2023121400

Let me know if you need any additional information.

Best regards,

Michael Milette

**Comment by jrchamp** [comment]
Thanks @michael-milette

Looks like this is a regression from #505, the registration upgrade line was unintentionally modified, likely because it also mentioned that the field was after option_auto_recording.

To resolve, we will want to:

- Undo the changes to that line in db/upgrade.php
- Add a new upgrade step for the upcoming release that sets the column to the expected definition
